### ISSUE TITLE
Key Press Not Detected by Event Viewer for Peripheral Huion Keydial mini K20

### ISSUE THREAD

**Issue by davidleejy** [pqrs-org/Karabiner-Elements#4033]
I am experiencing an issue with my Huion Keydial mini K20 device (link to Huion's official page for this device: https://store.huion.com/products/huion-keydial-mini). Although the device is recognized by Karabiner, its key presses do not appear in the Karabiner Event Viewer. This makes it impossible to remap or interact with the device’s inputs using Karabiner.

This device is visible to Karabiner as the Device log can attest:

```yaml
{
    "device_id": 42950xxxxx,
    "device_identifiers": {
        "is_keyboard": true,
        "is_pointing_device": true,
        "product_id": 33361,
        "vendor_id": 9580
    },
    "location_id": 348xxxxx,
    "manufacturer": "HUION",
    "product": "Keydial mini-642",
    "transport": "Bluetooth Low Energy"
}
```

This device is detected as both a keyboard and pointing device.

Despite detection, no key press events are displayed in the Karabiner Event Viewer when interacting with this device.

Karabiner Version: 15.3.0
Mac OS Version: 15.1.1 (24B91)
Mac CPU: Apple M3 Pro
